return [
  { id: '1', name: 'T-Shirt', category: 'Apparel', brand: 'Fashionista', color: 'Red', size: 'M', price: 19.99, quantity: 100, sold: 7, toCome: 24 },
  { id: '2', name: 'Jacket', category: 'Apparel', brand: 'OutdoorGear', color: 'Black', size: 'L', price: 79.99, quantity: 50, sold: 6, toCome: 9 },
  { id: '3', name: 'Running Shoes', category: 'Footwear', brand: 'SportyFeet', color: 'White', size: '9', price: 49.99, quantity: 75, sold: 24, toCome: 13 },
  { id: '4', name: 'Backpack', category: 'Accessories', brand: 'AdventureSeeker', color: 'Blue', size: 'One Size', price: 29.99, quantity: 30, sold: 5, toCome: 7 },
  { id: '5', name: 'Jeans', category: 'Apparel', brand: 'DenimCo', color: 'Dark Blue', size: '32/32', price: 39.99, quantity: 60, sold: 15, toCome: 7 },
  { id: '6', name: 'Sneakers', category: 'Footwear', brand: 'UrbanKicks', color: 'Black/White', size: '10', price: 59.99, quantity: 45, sold: 2, toCome: 0 },
  { id: '7', name: 'Smartphone', category: 'Electronics', brand: 'TechGizmo', color: 'Silver', size: 'One Size', price: 599.99, quantity: 20, sold: 4, toCome: 3 },
  { id: '8', name: 'Dress', category: 'Apparel', brand: 'ElegantWear', color: 'Pink', size: 'S', price: 69.99, quantity: 40, sold: 12, toCome: 6 },
  { id: '9', name: 'Headphones', category: 'Electronics', brand: 'SoundMaster', color: 'Black', size: 'One Size', price: 79.99, quantity: 25, sold: 0, toCome: 6 },
  { id: '10', name: 'Sunglasses', category: 'Accessories', brand: 'ShadeMasters', color: 'Brown', size: 'One Size', price: 19.99, quantity: 60, sold: 6, toCome: 2 },
  { id: '11', name: 'Sweater', category: 'Apparel', brand: 'CozyKnits', color: 'Gray', size: 'M', price: 49.99, quantity: 55, sold: 3, toCome: 3 },
  { id: '12', name: 'Running Shorts', category: 'Apparel', brand: 'SpeedyLegs', color: 'Black', size: 'L', price: 29.99, quantity: 70, sold: 9, toCome: 21 },
  { id: '13', name: 'Hiking Boots', category: 'Footwear', brand: 'TrailBlazers', color: 'Brown', size: '11', price: 89.99, quantity: 40, sold: 19, toCome: 7 },
  { id: '14', name: 'Watch', category: 'Accessories', brand: 'TimeKeeper', color: 'Silver', size: 'One Size', price: 99.99, quantity: 30, sold: 10, toCome: 3 },
  { id: '15', name: 'Hoodie', category: 'Apparel', brand: 'UrbanStyle', color: 'Navy Blue', size: 'XL', price: 34.99, quantity: 45, sold: 9, toCome: 12 },
  { id: '16', name: 'Running Jacket', category: 'Apparel', brand: 'SpeedyLegs', color: 'Yellow', size: 'M', price: 59.99, quantity: 60, sold: 1, toCome: 14 },
  { id: '17', name: 'Sneakers', category: 'Footwear', brand: 'SportyFeet', color: 'Red/Black', size: '9', price: 54.99, quantity: 50, sold: 23, toCome: 6 },
  { id: '18', name: 'Tablet', category: 'Electronics', brand: 'TechGizmo', color: 'Black', size: 'One Size', price: 299.99, quantity: 25, sold: 12, toCome: 4 },
  { id: '19', name: 'Trench Coat', category: 'Apparel', brand: 'ElegantWear', color: 'Beige', size: 'L', price: 149.99, quantity: 20, sold: 7, toCome: 4 },
  { id: '20', name: 'Earrings', category: 'Accessories', brand: 'GlamourJewels', color: 'Gold', size: 'One Size', price: 29.99, quantity: 100, sold: 41, toCome: 29 },
  { id: '21', name: 'Hiking Backpack', category: 'Accessories', brand: 'TrailBlazers', color: 'Green', size: 'One Size', price: 69.99, quantity: 30, sold: 4, toCome: 7 },
  { id: '22', name: 'Dress Shirt', category: 'Apparel', brand: 'ClassyWear', color: 'White', size: 'M', price: 44.99, quantity: 65, sold: 18, toCome: 7 },
  { id: '23', name: 'Running Socks', category: 'Footwear', brand: 'SpeedyLegs', color: 'White', size: 'One Size', price: 9.99, quantity: 120, sold: 45, toCome: 37 },
  { id: '24', name: 'Laptop', category: 'Electronics', brand: 'TechGizmo', color: 'Silver', size: 'One Size', price: 899.99, quantity: 15, sold: 1, toCome: 0 },
  { id: '25', name: 'Leather Wallet', category: 'Accessories', brand: 'ClassicLeather', color: 'Brown', size: 'One Size', price: 24.99, quantity: 80, sold: 3, toCome: 9 },
  { id: '26', name: 'Polo Shirt', category: 'Apparel', brand: 'CasualWear', color: 'Blue', size: 'S', price: 29.99, quantity: 75, sold: 7, toCome: 14 },
  { id: '27', name: 'Running Cap', category: 'Accessories', brand: 'SpeedyLegs', color: 'Black', size: 'One Size', price: 12.99, quantity: 90, sold: 24, toCome: 13 },
  { id: '28', name: 'Running Leggings', category: 'Apparel', brand: 'SpeedyLegs', color: 'Purple', size: 'M', price: 24.99, quantity: 70, sold: 23, toCome: 6 },
  { id: '29', name: 'Tennis Racket', category: 'Sports Equipment', brand: 'AceSports', color: 'Red/White', size: 'One Size', price: 59.99, quantity: 40, sold: 18, toCome: 6 },
  { id: '30', name: 'Sweatpants', category: 'Apparel', brand: 'ComfortFit', color: 'Gray', size: 'L', price: 34.99, quantity: 55, sold: 0, toCome: 8 },
  { id: '31', name: 'Smartwatch', category: 'Electronics', brand: 'TechGizmo', color: 'Black', size: 'One Size', price: 199.99, quantity: 30, sold: 4, toCome: 2 },
  { id: '32', name: 'Ski Jacket', category: 'Apparel', brand: 'SlopeMaster', color: 'Blue', size: 'XL', price: 149.99, quantity: 25, sold: 3, toCome: 4 },
  { id: '33', name: 'Running Gloves', category: 'Apparel', brand: 'SpeedyLegs', color: 'Black', size: 'M', price: 14.99, quantity: 80, sold: 9, toCome: 8 },
  { id: '34', name: 'Sports Bra', category: 'Apparel', brand: 'ActiveLife', color: 'Pink', size: 'M', price: 19.99, quantity: 65, sold: 13, toCome: 9 },
  { id: '35', name: 'Running Belt', category: 'Accessories', brand: 'SpeedyLegs', color: 'Black', size: 'One Size', price: 9.99, quantity: 100, sold: 48, toCome: 10 },
  { id: '36', name: 'Winter Boots', category: 'Footwear', brand: 'WarmFeet', color: 'Black', size: '8', price: 69.99, quantity: 30, sold: 6, toCome: 5 },
  { id: '37', name: 'Camera', category: 'Electronics', brand: 'PhotoPro', color: 'Black', size: 'One Size', price: 499.99, quantity: 15, sold: 3, toCome: 2 },
  { id: '38', name: 'Necktie', category: 'Accessories', brand: 'ElegantWear', color: 'Blue', size: 'One Size', price: 14.99, quantity: 90, sold: 16, toCome: 8 },
  { id: '39', name: 'Running Water Bottle', category: 'Accessories', brand: 'SpeedyLegs', color: 'Blue', size: 'One Size', price: 5.99, quantity: 150, sold: 12, toCome: 45 },
  { id: '40', name: 'Hiking Pants', category: 'Apparel', brand: 'TrailBlazers', color: 'Brown', size: '32/32', price: 44.99, quantity: 50, sold: 18, toCome: 8 },
  { id: '41', name: 'Baseball Cap', category: 'Accessories', brand: 'SportyFeet', color: 'Black', size: 'One Size', price: 9.99, quantity: 80, sold: 30, toCome: 8 },
  { id: '42', name: 'Duffel Bag', category: 'Accessories', brand: 'AdventureSeeker', color: 'Green', size: 'One Size', price: 39.99, quantity: 40, sold: 3, toCome: 8 },
  { id: '43', name: 'Yoga Mat', category: 'Fitness Equipment', brand: 'ZenBalance', color: 'Purple', size: 'One Size', price: 24.99, quantity: 60, sold: 18, toCome: 6 },
  { id: '44', name: 'Dinnerware Set', category: 'Home Goods', brand: 'HomeElegance', color: 'White', size: 'One Size', price: 69.99, quantity: 30, sold: 5, toCome: 6 },
  { id: '45', name: 'Leather Belt', category: 'Accessories', brand: 'ClassicLeather', color: 'Black', size: 'One Size', price: 19.99, quantity: 70, sold: 11, toCome: 4 },
  { id: '46', name: 'Winter Scarf', category: 'Accessories', brand: 'WarmFeet', color: 'Gray', size: 'One Size', price: 14.99, quantity: 80, sold: 14, toCome: 19 },
  { id: '47', name: 'Camping Tent', category: 'Outdoor Gear', brand: 'AdventureSeeker', color: 'Green/Orange', size: '2-Person', price: 129.99, quantity: 25, sold: 3, toCome: 7 },
  { id: '48', name: 'Blender', category: 'Kitchen Appliances', brand: 'KitchenMaster', color: 'Silver', size: 'One Size', price: 39.99, quantity: 40, sold: 15, toCome: 9 },
  { id: '49', name: 'Winter Gloves', category: 'Apparel', brand: 'WarmFeet', color: 'Black', size: 'L', price: 19.99, quantity: 90, sold: 8, toCome: 24 },
  { id: '50', name: 'Golf Clubs Set', category: 'Sports Equipment', brand: 'ProGolf', color: 'Black/Gold', size: 'One Size', price: 299.99, quantity: 15, sold: 1, toCome: 4 },
  { id: '51', name: 'Cookware Set', category: 'Kitchen Appliances', brand: 'KitchenMaster', color: 'Stainless Steel', size: 'One Size', price: 149.99, quantity: 20, sold: 3, toCome: 0 },
  { id: '52', name: 'Digital Camera', category: 'Electronics', brand: 'PhotoPro', color: 'Black', size: 'One Size', price: 449.99, quantity: 10, sold: 0, toCome: 3 },
  { id: '53', name: 'Umbrella', category: 'Accessories', brand: 'RainyDays', color: 'Blue', size: 'One Size', price: 12.99, quantity: 50, sold: 2, toCome: 14 },
  { id: '54', name: 'Ski Pants', category: 'Apparel', brand: 'SlopeMaster', color: 'Black', size: 'L', price: 79.99, quantity: 30, sold: 9, toCome: 7 },
  { id: '55', name: 'Fitness Tracker', category: 'Electronics', brand: 'FitTech', color: 'Black', size: 'One Size', price: 49.99, quantity: 40, sold: 9, toCome: 0 },
  { id: '56', name: 'Camping Sleeping Bag', category: 'Outdoor Gear', brand: 'AdventureSeeker', color: 'Green', size: 'One Size', price: 69.99, quantity: 20, sold: 7, toCome: 0 },
  { id: '57', name: 'Coffee Maker', category: 'Kitchen Appliances', brand: 'KitchenMaster', color: 'Black', size: 'One Size', price: 29.99, quantity: 25, sold: 8, toCome: 6 },
  { id: '58', name: 'Hiking Backpack', category: 'Outdoor Gear', brand: 'TrailBlazers', color: 'Black', size: 'One Size', price: 59.99, quantity: 35, sold: 3, toCome: 8 },
  { id: '59', name: 'Sweatshirt', category: 'Apparel', brand: 'ComfortFit', color: 'Gray', size: 'M', price: 29.99, quantity: 45, sold: 7, toCome: 7 },
  { id: '60', name: 'Dining Table', category: 'Home Goods', brand: 'HomeElegance', color: 'Wood', size: '6-Person', price: 249.99, quantity: 10, sold: 2, toCome: 3 },
  { id: '61', name: 'Wristwatch', category: 'Accessories', brand: 'TimeKeeper', color: 'Gold', size: 'One Size', price: 69.99, quantity: 15, sold: 1, toCome: 2 },
  { id: '62', name: 'Raincoat', category: 'Apparel', brand: 'RainyDays', color: 'Yellow', size: 'M', price: 39.99, quantity: 40, sold: 17, toCome: 3 },
  { id: '63', name: 'Yoga Blocks', category: 'Fitness Equipment', brand: 'ZenBalance', color: 'Purple', size: 'One Size', price: 9.99, quantity: 70, sold: 7, toCome: 1 },
  { id: '64', name: 'Vacuum Cleaner', category: 'Home Appliances', brand: 'CleanMaster', color: 'White', size: 'One Size', price: 149.99, quantity: 25, sold: 5, toCome: 5 },
  { id: '65', name: 'Ski Goggles', category: 'Outdoor Gear', brand: 'SlopeMaster', color: 'Blue', size: 'One Size', price: 34.99, quantity: 35, sold: 10, toCome: 0 },
  { id: '66', name: 'Tennis Balls', category: 'Sports Equipment', brand: 'AceSports', color: 'Yellow', size: 'Standard', price: 7.99, quantity: 100, sold: 20, toCome: 3 },
  { id: '67', name: 'Earmuffs', category: 'Accessories', brand: 'WarmFeet', color: 'Black', size: 'One Size', price: 9.99, quantity: 80, sold: 6, toCome: 25 },
  { id: '68', name: 'Kitchen Knife Set', category: 'Kitchen Appliances', brand: 'KitchenMaster', color: 'Silver', size: 'One Size', price: 29.99, quantity: 40, sold: 18, toCome: 10 },
  { id: '69', name: 'Climbing Harness', category: 'Outdoor Gear', brand: 'MountainTrek', color: 'Red/Black', size: 'One Size', price: 54.99, quantity: 25, sold: 1, toCome: 1 },
  { id: '70', name: 'Digital Scale', category: 'Home Appliances', brand: 'SmartLiving', color: 'White', size: 'One Size', price: 19.99, quantity: 50, sold: 23, toCome: 16 },
  { id: '71', name: 'Pencil Set', category: 'Office Supplies', brand: 'WriteRight', color: 'Assorted', size: 'One Size', price: 4.99, quantity: 200, sold: 22, toCome: 62 },
  { id: '72', name: 'Desk Chair', category: 'Furniture', brand: 'OfficeComfort', color: 'Black', size: 'One Size', price: 79.99, quantity: 20, sold: 2, toCome: 3 },
  { id: '73', name: 'Puzzle Set', category: 'Toys', brand: 'MindGames', color: 'Multicolor', size: 'One Size', price: 19.99, quantity: 30, sold: 5, toCome: 9 },
  { id: '74', name: 'Sunscreen Lotion', category: 'Health & Beauty', brand: 'SunGuard', color: 'White', size: '8 oz', price: 9.99, quantity: 100, sold: 44, toCome: 18 },
  { id: '75', name: 'Laptop Bag', category: 'Accessories', brand: 'TechGear', color: 'Gray', size: 'One Size', price: 24.99, quantity: 40, sold: 7, toCome: 5 },
  { id: '76', name: 'Baby Stroller', category: 'Baby Products', brand: 'LittleOnes', color: 'Blue', size: 'One Size', price: 149.99, quantity: 15, sold: 5, toCome: 0 },
  { id: '77', name: 'Wireless Mouse', category: 'Electronics', brand: 'TechGear', color: 'Black', size: 'One Size', price: 19.99, quantity: 50, sold: 24, toCome: 13 },
  { id: '78', name: 'Charging Cable', category: 'Electronics', brand: 'TechGear', color: 'White', size: 'One Size', price: 9.99, quantity: 100, sold: 27, toCome: 8 },
  { id: '79', name: 'Winter Hat', category: 'Apparel', brand: 'WarmFeet', color: 'Red', size: 'One Size', price: 12.99, quantity: 80, sold: 23, toCome: 7 },
  { id: '80', name: 'Guitar', category: 'Musical Instruments', brand: 'MusicMasters', color: 'Sunburst', size: 'One Size', price: 199.99, quantity: 10, sold: 0, toCome: 0 },
  { id: '81', name: 'Candles', category: 'Home Goods', brand: 'CozyHome', color: 'Vanilla', size: 'One Size', price: 14.99, quantity: 100, sold: 16, toCome: 22 },
  { id: '82', name: 'Dog Leash', category: 'Pet Supplies', brand: 'PetPals', color: 'Red', size: 'One Size', price: 9.99, quantity: 60, sold: 17, toCome: 13 },
  { id: '83', name: 'Bluetooth Speaker', category: 'Electronics', brand: 'SoundMaster', color: 'Black', size: 'One Size', price: 39.99, quantity: 30, sold: 2, toCome: 4 },
  { id: '84', name: 'Bicycle', category: 'Sports Equipment', brand: 'RideOn', color: 'Blue', size: '26-inch', price: 199.99, quantity: 15, sold: 1, toCome: 1 },
  { id: '85', name: 'Cooking Pot Set', category: 'Kitchen Appliances', brand: 'KitchenMaster', color: 'Stainless Steel', size: 'One Size', price: 49.99, quantity: 40, sold: 10, toCome: 11 },
  { id: '86', name: 'Yoga Mat Bag', category: 'Fitness Equipment', brand: 'ZenBalance', color: 'Black', size: 'One Size', price: 19.99, quantity: 60, sold: 15, toCome: 17 },
  { id: '87', name: 'Umbrella', category: 'Accessories', brand: 'RainyDays', color: 'Red', size: 'One Size', price: 12.99, quantity: 50, sold: 15, toCome: 9 },
  { id: '88', name: 'Ski Gloves', category: 'Outdoor Gear', brand: 'SlopeMaster', color: 'Black', size: 'M', price: 24.99, quantity: 70, sold: 17, toCome: 4 },
  { id: '89', name: 'Teapot', category: 'Kitchen Appliances', brand: 'TeaLovers', color: 'White', size: 'One Size', price: 14.99, quantity: 100, sold: 2, toCome: 13 },
  { id: '90', name: 'Basketball', category: 'Sports Equipment', brand: 'SportyFeet', color: 'Orange', size: 'Official', price: 14.99, quantity: 80, sold: 16, toCome: 21 },
  { id: '91', name: 'Dinnerware Set', category: 'Home Goods', brand: 'HomeElegance', color: 'Blue', size: 'One Size', price: 69.99, quantity: 30, sold: 8, toCome: 9 },
  { id: '92', name: 'Scissors', category: 'Office Supplies', brand: 'WriteRight', color: 'Black', size: 'One Size', price: 2.99, quantity: 200, sold: 17, toCome: 27 },
  { id: '93', name: 'Camping Cookware Set', category: 'Outdoor Gear', brand: 'AdventureSeeker', color: 'Black', size: 'One Size', price: 49.99, quantity: 35, sold: 12, toCome: 9 },
  { id: '94', name: 'Handbag', category: 'Accessories', brand: 'Fashionista', color: 'Pink', size: 'One Size', price: 29.99, quantity: 60, sold: 28, toCome: 17 },
  { id: '95', name: 'Electric Toothbrush', category: 'Health & Beauty', brand: 'DentalCare', color: 'White', size: 'One Size', price: 39.99, quantity: 40, sold: 5, toCome: 11 },
  { id: '96', name: 'Hiking Hat', category: 'Outdoor Gear', brand: 'TrailBlazers', color: 'Gray', size: 'One Size', price: 12.99, quantity: 75, sold: 17, toCome: 11 },
  { id: '97', name: 'Laptop Stand', category: 'Accessories', brand: 'TechGear', color: 'Silver', size: 'One Size', price: 19.99, quantity: 50, sold: 16, toCome: 13 },
  { id: '98', name: 'Dog Bed', category: 'Pet Supplies', brand: 'PetPals', color: 'Brown', size: 'Medium', price: 24.99, quantity: 40, sold: 15, toCome: 8 },
  { id: '99', name: 'Wireless Earbuds', category: 'Electronics', brand: 'SoundMaster', color: 'White', size: 'One Size', price: 49.99, quantity: 30, sold: 6, toCome: 6 },
  { id: '100', name: 'Gym Bag', category: 'Fitness Equipment', brand: 'FitTech', color: 'Black', size: 'One Size', price: 29.99, quantity: 50, sold: 15, toCome: 8 },
];